sudo: required
services:
  - docker

before_install:
  - docker build -t radhakrishna1979/new-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true radhakrishna1979/new-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "my-react-app"
  env: "Myreactapp-env"
  bucket_name: "elasticbeanstalk-us-west-2-319762603406"
  bucket_path: "my-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY